cmake_minimum_required(VERSION 3.9)

set(TOOLCHAIN_C_COMPILER ${NATIVE_C_COMPILER})
set(TOOLCHAIN_CXX_COMPILER ${NATIVE_CXX_COMPILER})
set(TOOLCHAIN_ASM_COMPILER ${NATIVE_C_COMPILER})

set(TOOLCHAIN_C_LINK_CMD ${NATIVE_C_LINK_EXECUTABLE})
set(TOOLCHAIN_CXX_LINK_CMD ${NATIVE_CXX_LINK_EXECUTABLE})
set(TOOLCHAIN_ASM_LINK_CMD ${NATIVE_ASM_LINK_EXECUTABLE})

set(TOOLCHAIN_AR ${NATIVE_AR})
set(TOOLCHAIN_RANLIB ${NATIVE_RANLIB})
