cmake_minimum_required(VERSION 3.9)

set(PLATFORM_DEFAULT_TOOLCHAIN native)

set(PLATFORM_C_FLAGS "${NATIVE_C_FLAGS}")
set(PLATFORM_CXX_FLAGS "${NATIVE_CXX_FLAGS}")
set(PLATFORM_ASM_FLAGS "${NATIVE_ASM_FLAGS}")

set(PLATFORM_C_LINK_FLAGS "${NATIVE_C_LINK_FLAGS}")
set(PLATFORM_CXX_LINK_FLAGS "${NATIVE_CXX_LINK_FLAGS}")
set(PLATFORM_ASM_LINK_FLAGS "${NATIVE_ASM_LINK_FLAGS}")
