cmake_minimum_required(VERSION 3.9)

function(download NAME URL FILE_CHECKSUM FILE)
    if (EXISTS ${FILE})
        #file(SHA256 "${FILE}" DOWNLOAD_CHECKSUM)
    endif()
    if (EXISTS ${FILE})# AND "${FILE_CHECKSUM}" EQUAL "${DOWNLOAD_CHECKSUM}")
        #message("Already downloaded ${NAME}")
    else()
        message("Downloading ${NAME}...")
        execute_process(COMMAND "curl" "-L" "${URL}" "--output" "${FILE}" "--progress-bar")
        message("Downloaded ${NAME}")
    endif()
endfunction(download)

function(unzip NAME FILE WORKING_DIRECTORY FINAL_DIR)
    if (EXISTS ${FINAL_DIR})
        #message("Already unziped ${NAME}")
    else()
        message("Unzipping ${NAME}...")
        execute_process(COMMAND "unzip" "${FILE}"
            WORKING_DIRECTORY "${WORKING_DIRECTORY}" OUTPUT_QUIET)
        message("Unziped ${NAME}")
    endif()
endfunction(unzip)

function(patch PATCH_FILE WORKING_DIRECTORY)
    execute_process(COMMAND "patch" "-s" "-p0" "-i" "${PATCH_FILE}"
        WORKING_DIRECTORY "${WORKING_DIRECTORY}" OUTPUT_QUIET)
endfunction(patch)
